[ package ]
name = "rusty"
version = "0.1.0"
edition = "2021"
authors = ["Nerap <44852526+nerap@users.noreply.github.com>"]
description = "A neural network based trading bot"

[ dependencies ]
rand = "0.8.5"
chrono = "0.4.31"

# Optional but recommended for development
[ dev-dependencies ]
criterion = "0.5"

[ profile.release ]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[ profile.dev ]
opt-level = 1
